name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        working-directory: AndroidXml.Tests
        run: |
          dotnet test

      - name: Build
        working-directory: AndroidXml
        run: |
          dotnet pack -c Release -o ${{ github.workspace }}/bin/

      - name: Upload NuGet package
        uses: actions/upload-artifact@v2
        with:
          name: androidxml
          path: |
            ${{ github.workspace }}/bin/
